plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

apply from: rootProject.file("gradle/android-library-common.gradle")

android {
    namespace "com.novel.feature.search"
    configureNovelAndroidLibrary(delegate, false)
}

dependencies {
    implementation project(':core-common')
    implementation project(':core-storage')
    implementation "androidx.compose.runtime:runtime:1.8.2"
    implementation "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
    implementation "javax.inject:javax.inject:1"

    testImplementation "junit:junit:4.13.2"
    testImplementation "com.google.truth:truth:1.4.4"
}
