plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

apply from: rootProject.file("gradle/android-library-common.gradle")

android {
    namespace "com.novel.feature.welfare"
    configureNovelAndroidLibrary(delegate, false)
}

dependencies {
    implementation "androidx.compose.runtime:runtime:1.8.2"
    implementation "androidx.compose.ui:ui:1.8.2"
    implementation "androidx.compose.foundation:foundation:1.8.2"
    implementation "androidx.compose.material3:material3-android:1.3.2"
    implementation "androidx.compose.material:material-icons-extended:1.7.6"

    testImplementation "junit:junit:4.13.2"
}
